### ISSUE TITLE
Width of double-width characters is wrong.

### ISSUE THREAD

**Issue by rhysd** [rhysd/neovim-component#17]
It seems that width of double-width character is narrower than double width of normal character.  It causes the wrong cursor position as below.

![tmp](https://cloud.githubusercontent.com/assets/823277/12642843/a86bb722-c5fb-11e5-97ec-d8cec2dc33fc.gif)

**Comment by rhysd** [comment]
I currently don't have any idea except for rendering text per one character to resolve this issue.

**Comment by romgrk** [comment]
On the same subject (I'm not opening a new issue because issues are not pretty but if you think it should be opened I'll do):
When rendering double-width chars, updates don´t cover fully the area previously drawn, therefore there are “leftovers” still drawn on screen until some other update covers completely the area. Maybe doing some more rendering than what is asked by neovim could solve this.

**Comment by rhysd** [comment]
Yes, I think we should render text per character.  I think it is not so hard and I'll try it.

**Comment by rhysd** [comment]
I'm working on this in [issue17 branch](https://github.com/rhysd/neovim-component/tree/issue17).

And it seems to work well:

![tmp](https://cloud.githubusercontent.com/assets/823277/12945196/3293d33e-d02f-11e5-8c66-69308671ec14.gif)

And I also added support surrogate pair characters such as '𠮟'.  It seems to work well but emojis are not rendered properly.  This looks a limitation of Vim.

<img width="65" alt="2016-02-10 18 51 38" src="https://cloud.githubusercontent.com/assets/823277/12945226/5e714dc4-d02f-11e5-817f-d8243b31dcb9.png">
