### ISSUE TITLE
installation issue under Windows

### ISSUE THREAD

**Issue by bon-ami** [rhysd/neovim-component#51]
portable node.js LTS 10.16.3
nyaovim  0.2.0 installed

run "npm install neovim-component" (0.10.1) and it reports following. 
npm WARN deprecated core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-j
s@3 or at least to actual version of core-js@2.
npm WARN flux@3.1.3 requires a peer of react@^15.0.2 || ^16.0.0-beta || ^16.0.0 but none is installe
d. You must install peer dependencies yourself.

After successfully installed, when I run "nyaovim", its window content is blank and not interactive.

**Comment by bon-ami** [comment]
I installed it under node.js while I should have installed it under nyaovim

**Comment by rhysd** [comment]
> npm WARN deprecated core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-j
s@3 or at least to actual version of core-js@2.

It's just a deprecation warning so you can ignore it.

> npm WARN flux@3.1.3 requires a peer of react@^15.0.2 || ^16.0.0-beta || ^16.0.0 but none is installe
d. You must install peer dependencies yourself.

It's just a warning that React is not installed since flux is usually used with React. But it's not mandatory and actually this package does not use flux with React. So it can be ignored.
